### ISSUE TITLE
Compatibility scripts don't resolve

### ISSUE THREAD

**Issue by Jacky720** [UnderminersTeam/UndertaleModTool#481]
From `gml_Object_DEVICE_MENU_Draw_0` in _Deltarune_:
```gml
draw_background_part_ext(1008, 0, i, __WAVEWIDTH, 1, (sin(((i / 8) + (BG_SINER / 30))) * __WAVEMAG), ((-10 + i) - (BG_ALPHA * 20)), 1, 1, image_blend, (BG_ALPHA * 0.8))
```
The first parameter should resolve as `IMAGE_MENU`, but doesn't, because `draw_background_part_ext` is actually a compatibility script in Deltarune and not a function. This script (and similar scripts) should resolve in the tool.

**Comment by Jacky720** [comment]
Other ~~scripts suffering from this~~ asset resolver trip-ups include:

Deltarune:
`draw_background_ext` argument0, should be sprite.
`draw_background_tiled_ext` argument0, should be sprite.
`draw_set_blend_mode` argument0, should be [a blendmode constant](https://manual.yoyogames.com/GameMaker_Language/GML_Reference/Drawing/GPU_Control/gpu_set_blendmode.htm).
`d3d_set_fog` argument1, should be color.
`__background_set_element` argument13, should be color.

Some more complicated resolver problems I turned up:
`scr_roomname` argument0, should be room. This is mainly a concern _inside_ the script, with `if (argument0 == 2)`, `35`, and so on.
`ds_map_add`, exclusively in `scr_84_init_localization`, argument1 should be font.
`draw_rectangle` argument4, should be boolean.

Undertale:
`button` within `scr_getbuttonsprite` should be whatever these button constants are.
The return value of `scr_getbuttonsprite` should be sprite.
`draw_custom_ext` argument4 _does_ resolve as sprite, but for line 1 of the script it's supposed to be comparing `if (argument4 == 0)`. I have no clue how that could work.
Does `draw_getpixel` return a color already? Comparisons between a call of the script and `c_white` aren't resolving the latter in `obj_vaporized_old_Alarm_0`.
`obj_trashnado_Create_0` uses `choose` on sprites to set its `tsprX` variables; is it currently possible to resolve these through the function? I know this one is asking a lot.
Likewise setting `c.image_blend` in `obj_settingsmenu_Draw_0`, but for color.
And its duplicate in `obj_joypadmenu_Draw_0`.
And `image_blend` in `obj_melonbullet_Step_0`.
And `sprite_index` in  `obj_6heal_Create_0`.

...which is a lot to say that the problem mentioned originally has already been handled for Undertale.

**Comment by BenjaminUrquhart** [comment]
I believe `scr_getbuttonsprite` and `draw_set_blend_mode` are already fixed as of the latest master at the time of writing. I’ll take a look.

**Comment by Jacky720** [comment]
Just updated. You're correct, in addition to the resolution (ha ha) of the problem I had originally. I'll leave this open for the meantime because a few that still don't work look like easy fixes.

**Comment by Jacky720** [comment]
All of the `choose` issues are covered by #1689. That leaves scr_roomname, special cases for DS maps (see #578), and draw_getpixel.
